---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: redhat-family-instance
    image: centos:7
    privileged: True
    command: '/sbin/init'
    cap_add:
      - SYS_ADMIN
      - SETPCAP
  - name: debian-family-instance
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: '/sbin/init'
    capabilities:
      - SYS_ADMIN
      - SETPCAP
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
